<?php

namespace App\Services\Contracts;

use App\Enums\ContractStatus;
use App\Enums\NotificationType;
use App\Enums\TerminatedBy;
use App\Models\Admin;
use App\Models\Contract;
use App\Models\User;
use App\Services\AuditService;
use App\Services\NotificationService;

/**
 * ContractLifecycleService — the Contract Engine.
 *
 * The single, guarded home for every contract STATUS transition:
 * draft -> pending_tenant -> active -> terminated | expired. Before this engine
 * the transitions lived scattered across three controllers plus a command, each
 * doing its own `->update(['status' => ...])` + audit + notification with no
 * central guard, so nothing enforced which transitions are legal or kept the
 * audit/notification shape consistent.
 *
 * Boundaries — what this engine does and does NOT own:
 *  - It OWNS: the state guard (which statuses may transition where), the status
 *    mutation, the audit-log entry, and recipient notifications for each
 *    transition.
 *  - It does NOT own authorization. Controllers keep their policy checks
 *    (ownership + state) via $this->authorize(); this engine is a defense-in-depth
 *    invariant, not the gate. The authorization model is unchanged.
 *  - It does NOT generate rent. First-month rent is produced by ContractObserver
 *    when a contract becomes ACTIVE (wasJustActivated -> generateFirstRentEntry);
 *    accept() simply sets ACTIVE and the observer reacts. This engine must not
 *    duplicate that.
 *  - It does NOT own contract CREATION (a draft is created directly) or RENEWAL
 *    (which mutates dates, not status) — those are not status transitions.
 *
 * Every method returns the same Contract instance after the transition. Callers
 * that need fresh relations should ->fresh() as before.
 */
class ContractLifecycleService
{
    public function __construct(
        protected AuditService $auditService,
        protected NotificationService $notificationService,
    ) {}

    /**
     * Landlord sends a DRAFT contract to the tenant for signature.
     * draft -> pending_tenant.
     */
    public function send(Contract $contract, User $landlord): Contract
    {
        $this->guard($contract, ContractStatus::DRAFT, 'send');

        $contract->update([
            'status' => ContractStatus::PENDING_TENANT,
        ]);

        $this->auditService->log(
            actor: $landlord,
            action: 'contract_sent',
            subject: $contract,
            description: 'Sent contract to tenant for acceptance'
        );

        $eventId = "contract-sent:{$contract->id}";
        if (! $this->notificationService->exists($contract->tenant, $eventId)) {
            $this->notificationService->create(
                user: $contract->tenant,
                type: NotificationType::CONTRACT_SENT,
                title: 'New lease ready to sign',
                message: "A lease for \"{$contract->listing->title}\" is ready for your review and signature.",
                data: [
                    'event_id' => $eventId,
                    'contract_id' => $contract->id,
                ]
            );
        }

        return $contract;
    }

    /**
     * Tenant accepts a PENDING_TENANT contract, activating the tenancy.
     * pending_tenant -> active. First rent is generated by ContractObserver in
     * reaction to the status becoming ACTIVE — not here.
     */
    public function accept(Contract $contract, User $tenant): Contract
    {
        $this->guardWith($contract->status->canBeAccepted(), 'accept');

        $contract->update([
            'status' => ContractStatus::ACTIVE,
        ]);

        $this->auditService->log(
            actor: $tenant,
            action: 'contract_accepted',
            subject: $contract,
            description: 'Tenant accepted contract',
            severity: 'info'
        );

        $eventId = "contract-signed:{$contract->id}";
        if (! $this->notificationService->exists($contract->landlord, $eventId)) {
            $this->notificationService->create(
                user: $contract->landlord,
                type: NotificationType::CONTRACT_SIGNED,
                title: 'Contract Signed',
                message: "{$tenant->full_name} has accepted the contract for \"{$contract->listing->title}\".",
                data: [
                    'event_id' => $eventId,
                    'contract_id' => $contract->id,
                    'tenant_id' => $tenant->id,
                ]
            );
        }

        return $contract;
    }

    /**
     * Tenant terminates their own contract (ends an active lease early or
     * declines a pending one). Notifies the landlord.
     */
    public function terminateByTenant(Contract $contract, User $tenant, string $reason): Contract
    {
        $this->markTerminated($contract, TerminatedBy::TENANT, $reason);

        $this->auditService->log(
            actor: $tenant,
            action: 'contract_terminated',
            subject: $contract,
            description: 'Tenant terminated contract',
            severity: 'warning'
        );

        $eventId = "contract-terminated:{$contract->id}:landlord";
        if (! $this->notificationService->exists($contract->landlord, $eventId)) {
            $this->notificationService->create(
                user: $contract->landlord,
                type: NotificationType::CONTRACT_TERMINATED,
                title: 'Contract Terminated',
                message: "{$tenant->full_name} has terminated the contract for \"{$contract->listing->title}\". Reason: {$reason}",
                data: [
                    'event_id' => $eventId,
                    'contract_id' => $contract->id,
                    'terminated_by' => 'tenant',
                    'reason' => $reason,
                ]
            );
        }

        return $contract;
    }

    /**
     * Landlord terminates the contract. Notifies the tenant.
     */
    public function terminateByLandlord(Contract $contract, User $landlord, string $reason): Contract
    {
        $this->markTerminated($contract, TerminatedBy::LANDLORD, $reason);

        $this->auditService->log(
            actor: $landlord,
            action: 'contract_terminated',
            subject: $contract,
            description: 'Landlord terminated contract',
            severity: 'warning'
        );

        $eventId = "contract-terminated:{$contract->id}:tenant";
        if (! $this->notificationService->exists($contract->tenant, $eventId)) {
            $this->notificationService->create(
                user: $contract->tenant,
                type: NotificationType::CONTRACT_TERMINATED,
                title: 'Contract Terminated',
                message: "{$landlord->full_name} has terminated your contract for \"{$contract->listing->title}\". Reason: {$reason}",
                data: [
                    'event_id' => $eventId,
                    'contract_id' => $contract->id,
                    'terminated_by' => 'landlord',
                    'reason' => $reason,
                ]
            );
        }

        return $contract;
    }

    /**
     * Admin force-terminates the contract. Records admin_id, logs at critical
     * severity, and notifies BOTH parties.
     */
    public function forceTerminateByAdmin(Contract $contract, Admin $admin, string $reason): Contract
    {
        $this->markTerminated($contract, TerminatedBy::ADMIN, $reason, $admin);

        $this->auditService->log(
            actor: $admin,
            action: 'contract_force_terminated',
            subject: $contract,
            description: 'Admin force terminated contract',
            severity: 'critical'
        );

        $tenantEventId = "contract-terminated:{$contract->id}:tenant";
        if (! $this->notificationService->exists($contract->tenant, $tenantEventId)) {
            $this->notificationService->create(
                user: $contract->tenant,
                type: NotificationType::CONTRACT_TERMINATED,
                title: 'Contract Terminated',
                message: "Your contract for \"{$contract->listing->title}\" has been terminated by the platform. Reason: {$reason}",
                data: [
                    'event_id' => $tenantEventId,
                    'contract_id' => $contract->id,
                    'terminated_by' => 'admin',
                    'reason' => $reason,
                ]
            );
        }

        $landlordEventId = "contract-terminated:{$contract->id}:landlord";
        if (! $this->notificationService->exists($contract->landlord, $landlordEventId)) {
            $this->notificationService->create(
                user: $contract->landlord,
                type: NotificationType::CONTRACT_TERMINATED,
                title: 'Contract Terminated',
                message: "The contract for \"{$contract->listing->title}\" has been terminated by the platform. Reason: {$reason}",
                data: [
                    'event_id' => $landlordEventId,
                    'contract_id' => $contract->id,
                    'terminated_by' => 'admin',
                    'reason' => $reason,
                ]
            );
        }

        return $contract;
    }

    /**
     * Mark an ACTIVE contract EXPIRED once its end date has passed. Scheduled,
     * system-driven (no actor, no notification) — mirrors the existing
     * contracts:mark-expired command's behavior.
     */
    public function expire(Contract $contract): Contract
    {
        $this->guard($contract, ContractStatus::ACTIVE, 'expire');

        $contract->update([
            'status' => ContractStatus::EXPIRED,
        ]);

        $this->auditService->log(
            actor: null, // Scheduled system action
            action: 'contract_expired',
            subject: $contract,
            description: "Contract {$contract->id} reached its end date ({$contract->end_date->format('Y-m-d')}) and was marked expired",
            severity: 'info'
        );

        return $contract;
    }

    /**
     * Shared termination mechanic: guard, then set the terminal status +
     * terminated_by + reason (+ admin_id for admin-forced). Audit/notification
     * differ per actor and stay in the public methods above.
     */
    protected function markTerminated(Contract $contract, TerminatedBy $by, string $reason, ?Admin $admin = null): void
    {
        $this->guardWith($contract->status->canBeTerminated(), 'terminate');

        $attributes = [
            'status' => ContractStatus::TERMINATED,
            'terminated_by' => $by,
            'termination_reason' => $reason,
        ];

        if ($admin !== null) {
            $attributes['admin_id'] = $admin->id;
        }

        $contract->update($attributes);
    }

    /**
     * Guard a transition that is only legal from a single source status.
     */
    protected function guard(Contract $contract, ContractStatus $requiredFrom, string $transition): void
    {
        $this->guardWith($contract->status === $requiredFrom, $transition);
    }

    /**
     * Guard a transition against a precomputed condition, failing loudly.
     */
    protected function guardWith(bool $allowed, string $transition): void
    {
        if (! $allowed) {
            throw new InvalidContractTransitionException(
                "Contract cannot be transitioned via '{$transition}' from its current status."
            );
        }
    }
}
