<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Admin;
use App\Services\Admin\AdminAnalyticsService;
use App\Services\AuditService;
use App\Support\Csv\CsvWriter;
use Carbon\Carbon;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * AdminAnalyticsController
 *
 * GET /admin/analytics/admin-summary — the scoped "Admin Analytics" page: a
 * permission-aware work/risk dashboard for the SIGNED-IN admin, distinct from
 * the Super Admin "Platform Analytics" page (AdminAnalyticsOverviewController,
 * gated by admin.can:view_analytics). This route is deliberately reachable by
 * ANY authenticated admin — like GET /admin/dashboard — because every admin
 * needs visibility into their own review queues regardless of whether they
 * hold the platform-wide view_analytics capability. What differs per admin is
 * not whether the page opens, but which MODULE SECTIONS the response
 * contains: AdminAnalyticsService checks the admin's real capabilities and
 * omits a module entirely rather than exposing data they can't moderate.
 */
class AdminAnalyticsController extends Controller
{
    /** Named ranges the frontend's period selector maps to (mirrors AdminAnalyticsOverviewController). */
    private const RANGES = ['7d', '30d', '90d', 'this_month', 'last_month', 'ytd', 'custom'];

    public function __construct(
        private readonly AdminAnalyticsService $service,
        private readonly AuditService $auditService,
    ) {}

    public function summary(Request $request): JsonResponse
    {
        [$rangeKey, $dateFrom, $dateTo] = $this->resolveRange($this->validateRange($request));

        return response()->json([
            'range' => [
                'key' => $rangeKey,
                'start_date' => $dateFrom->toDateString(),
                'end_date' => $dateTo->toDateString(),
            ],
            'analytics' => $this->service->forAdmin($this->admin(), $dateFrom, $dateTo),
        ]);
    }

    /**
     * CSV export of this admin's scope summary and attention queue — audit
     * logged like the ledger export, since it moves data (albeit already
     * scoped to what this admin can see) out of the app.
     */
    public function export(Request $request): StreamedResponse
    {
        [$rangeKey, $dateFrom, $dateTo] = $this->resolveRange($this->validateRange($request));

        $admin = $this->admin();
        $analytics = $this->service->forAdmin($admin, $dateFrom, $dateTo);

        $this->auditService->log(
            actor: $admin,
            action: 'admin_analytics_exported',
            subject: null,
            description: 'Admin analytics summary exported ('.implode(', ', $analytics['scope']['permitted_modules']).').',
            severity: 'info',
            metadata: ['range' => $rangeKey, 'permitted_modules' => $analytics['scope']['permitted_modules']],
        );

        $rows = [
            ['Generated by', $admin->name],
            ['Generated at', $analytics['generated_at']],
            ['Range', "{$dateFrom->toDateString()} to {$dateTo->toDateString()}"],
            ['Permission scope', implode(', ', $analytics['scope']['permitted_modules'])],
            [],
            ['Attention item', 'Severity', 'Area', 'Detail', 'Age', 'Suggested action'],
        ];
        foreach ($analytics['attention'] as $item) {
            $rows[] = [$item['title'], $item['severity'], $item['area'], $item['subject'], $item['age'] ?? '', $item['action']];
        }

        $rows[] = [];
        // why: the on-screen "My decisions this period" card shows the full
        // decision count (decisions_period — listing/verification reviews PLUS
        // ledger actions like waives and late fees). The breakdown below is
        // narrower (review outcomes only: approvals/rejections/send-backs), so
        // it must NOT reuse the same "My decisions" label or the CSV total
        // silently disagrees with the screen. Emit the headline figure first,
        // then the review-outcome breakdown under its own honest heading.
        $rows[] = ['My decisions this period', $analytics['me']['decisions_period']];
        $rows[] = [];
        $rows[] = ['My review outcomes this period', 'Approved', 'Rejected', 'Sent back'];
        $rows[] = [
            'Total',
            $analytics['me']['outcome_totals']['approved'],
            $analytics['me']['outcome_totals']['rejected'],
            $analytics['me']['outcome_totals']['sent_back'],
        ];

        if (! empty($analytics['me']['top_reasons'])) {
            $rows[] = [];
            $rows[] = ['Common send-back / rejection reason', 'Count'];
            foreach ($analytics['me']['top_reasons'] as $reason) {
                $rows[] = [$reason['reason'], $reason['count']];
            }
        }

        return response()->streamDownload(function () use ($rows) {
            $out = fopen('php://output', 'w');
            foreach ($rows as $row) {
                fputcsv($out, CsvWriter::sanitizeRow($row));
            }
            fclose($out);
        }, 'wyncrest-admin-analytics.csv', ['Content-Type' => 'text/csv']);
    }

    private function admin(): Admin
    {
        /** @var Admin $admin */
        $admin = auth('admin')->user();

        return $admin;
    }

    private function validateRange(Request $request): array
    {
        return $request->validate([
            'range' => ['nullable', 'in:'.implode(',', self::RANGES)],
            'start_date' => ['nullable', 'date', 'required_if:range,custom'],
            'end_date' => ['nullable', 'date', 'after_or_equal:start_date'],
        ]);
    }

    /**
     * @return array{0:string,1:Carbon,2:Carbon}
     */
    private function resolveRange(array $validated): array
    {
        $range = $validated['range'] ?? '30d';

        if ($range === 'custom') {
            return [$range, Carbon::parse($validated['start_date']), Carbon::parse($validated['end_date'] ?? now())];
        }

        return match ($range) {
            '7d' => [$range, now()->subDays(7)->startOfDay(), now()->endOfDay()],
            '90d' => [$range, now()->subDays(90)->startOfDay(), now()->endOfDay()],
            'this_month' => [$range, now()->startOfMonth(), now()->endOfMonth()],
            'last_month' => [$range, now()->subMonthNoOverflow()->startOfMonth(), now()->subMonthNoOverflow()->endOfMonth()],
            'ytd' => [$range, now()->startOfYear(), now()->endOfDay()],
            default => [$range, now()->subDays(30)->startOfDay(), now()->endOfDay()],
        };
    }
}
